#!/usr/bin/env python3
"""Generate C++ oracle-record tables from the JSON oracle specs.

The JSON files under src/oracles/specs/ are the source of truth for oracle
claims, evidence classes, source references, limitations, and execution
metadata.  This script materializes them into checked-in C++ include files so
the runtime does not need a JSON dependency.

Usage:
    python3 scripts/generate_oracle_specs.py            # write generated files
    python3 scripts/generate_oracle_specs.py --check    # fail if stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SPECS_DIR = REPO_ROOT / "src" / "oracles" / "specs"
FIPS_OUTPUT = REPO_ROOT / "src" / "oracles" / "generated_fips_specs.inc"
METAMORPHIC_OUTPUT = REPO_ROOT / "src" / "oracles" / "generated_metamorphic_specs.inc"

FIPS_FILES = [
    "ml_kem.json",
    "ml_dsa.json",
    "slh_dsa.json",
    "aigis_enc.json",
    "aigis_sig.json",
]
METAMORPHIC_FILES = [
    "metamorphic_kem.json",
    "metamorphic_sig.json",
]

EVIDENCE_CLASSES = {
    "NORMATIVE": "EvidenceClass::kNormative",
    "REFERENCE_DERIVED": "EvidenceClass::kReferenceDerived",
    "IMPLEMENTATION_OBSERVED": "EvidenceClass::kImplementationObserved",
    "ENGINEERING_RECOMMENDATION": "EvidenceClass::kEngineeringRecommendation",
    "INFERENCE": "EvidenceClass::kInference",
}

RELATION_NAMES = {
    "SAME_SHARED_SECRET",
    "DIFFERENT_SHARED_SECRET",
    "NO_CRASH",
    "NO_TIMEOUT",
    "NO_OUTPUT_ON_ALLOCATION_FAILURE",
    "REJECT_OR_DIFFERENT_SHARED_SECRET",
    "VERIFY_TRUE",
    "VERIFY_FALSE",
    "DECODE_REJECT",
    "VERIFY_FALSE_OR_DECODE_REJECT_OR_API_INVALID_INPUT",
    "VERIFY_FALSE_OR_API_UNSUPPORTED",
    "REJECT_OR_INVALID_INPUT",
    "REJECT_WITH_CONSISTENT_OUTPUT_LENGTH_STATE",
    "EXPECT_EQUAL",
    "EXPECT_DIFFERENT",
    "UNKNOWN",
}

HEADER = "// Generated by scripts/generate_oracle_specs.py. DO NOT EDIT.\n"


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def cpp_string_list(values: list[str]) -> str:
    if not values:
        return "{}"
    return "{" + ", ".join(cpp_string(value) for value in values) + "}"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"oracle spec error: {message}")


def read_specs(files: list[str], *, metamorphic: bool) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for name in files:
        path = SPECS_DIR / name
        payload = json.loads(path.read_text(encoding="utf-8"))
        require(isinstance(payload, dict), f"{name}: root must be an object")
        entries = payload.get("oracles")
        require(isinstance(entries, list), f"{name}: 'oracles' must be an array")
        for entry in entries:
            require(isinstance(entry, dict), f"{name}: oracle entries must be objects")
            oracle_id = entry.get("oracle_id")
            require(isinstance(oracle_id, str) and oracle_id, f"{name}: missing oracle_id")
            claim = entry.get("claim")
            require(isinstance(claim, str) and claim, f"{oracle_id}: missing claim")
            evidence = entry.get("evidence_class")
            require(evidence in EVIDENCE_CLASSES, f"{oracle_id}: bad evidence_class {evidence!r}")
            source = entry.get("source_reference")
            require(isinstance(source, str) and source, f"{oracle_id}: missing source_reference")
            if metamorphic:
                require(isinstance(entry.get("field"), str), f"{oracle_id}: missing field")
                require(
                    isinstance(entry.get("finding_subclass"), str),
                    f"{oracle_id}: missing finding_subclass",
                )
            else:
                require(isinstance(entry.get("primitive_type"), str), f"{oracle_id}: missing primitive_type")
                require(
                    isinstance(entry.get("algorithm_family"), str),
                    f"{oracle_id}: missing algorithm_family",
                )
                relation = entry.get("expected_relation")
                require(relation in RELATION_NAMES, f"{oracle_id}: bad expected_relation {relation!r}")
            records.append(entry)
    return records


def emit_metadata(lines: list[str], entry: dict[str, Any]) -> None:
    limitations = entry.get("limitations", [])
    require(isinstance(limitations, list), f"{entry['oracle_id']}: limitations must be an array")
    for item in limitations:
        require(isinstance(item, str), f"{entry['oracle_id']}: limitations must be strings")
    scope = entry.get("scope", {})
    api_layer = entry.get("scope_api_layer", "")
    if isinstance(scope, dict):
        api_layer = scope.get("api_layer", api_layer)
    controls = entry.get("controls", {})
    positive = entry.get("positive_control", "")
    negative = entry.get("negative_control", "")
    if isinstance(controls, dict):
        positive = controls.get("positive_control", positive)
        negative = controls.get("negative_control", negative)
    lines.append(f"    spec.metadata.claim = {cpp_string(entry['claim'])};\n")
    lines.append(f"    spec.metadata.evidence_class = {EVIDENCE_CLASSES[entry['evidence_class']]};\n")
    lines.append(f"    spec.metadata.source_reference = {cpp_string(entry['source_reference'])};\n")
    lines.append(f"    spec.metadata.scope_api_layer = {cpp_string(str(api_layer))};\n")
    lines.append(f"    spec.metadata.limitations = {cpp_string_list(limitations)};\n")
    lines.append(
        f"    spec.metadata.conditional_verdict = {cpp_string(str(entry.get('conditional_verdict', '')))};\n"
    )
    lines.append(f"    spec.metadata.positive_control = {cpp_string(str(positive))};\n")
    lines.append(f"    spec.metadata.negative_control = {cpp_string(str(negative))};\n")


def emit_fips(records: list[dict[str, Any]]) -> str:
    lines = [HEADER, "\n", "static std::vector<OracleSpec> GeneratedFipsOracleSpecs() {\n", "  std::vector<OracleSpec> specs;\n"]
    for entry in records:
        precondition = entry.get("precondition", {})
        mutation = entry.get("mutation", {})
        lines.append("  {\n")
        lines.append("    OracleSpec spec;\n")
        lines.append(f"    spec.oracle_id = {cpp_string(entry['oracle_id'])};\n")
        lines.append(f"    spec.algorithm_family = {cpp_string(entry['algorithm_family'])};\n")
        lines.append(f"    spec.primitive_type = {cpp_string(entry['primitive_type'])};\n")
        api_surface = entry.get("api_surface", [])
        lines.append(f"    spec.api_surface = {cpp_string_list(api_surface)};\n")
        lines.append(f"    spec.mutation_type = {cpp_string(str(mutation.get('type', 'none')))};\n")
        targets = mutation.get("targets", [])
        lines.append(f"    spec.mutation_targets = {cpp_string_list(targets)};\n")
        lines.append(
            f"    spec.expected_relation = ExpectedRelationFromName({cpp_string(entry['expected_relation'])});\n"
        )
        lines.append(f"    spec.comparator = {cpp_string(str(entry.get('comparator', '')))};\n")
        lines.append(f"    spec.triage_policy = {cpp_string(str(entry.get('triage_policy', '')))};\n")
        lines.append(
            "    spec.precondition_json = "
            + cpp_string(json.dumps(precondition, sort_keys=True, separators=(",", ":")))
            + ";\n"
        )
        lines.append(
            f"    spec.enabled_by_default = {'false' if entry.get('enabled_by_default') is False else 'true'};\n"
        )
        lines.append(f"    spec.requires_api = {cpp_string(str(entry.get('requires_api', '')))};\n")
        emit_metadata(lines, entry)
        lines.append("    specs.push_back(std::move(spec));\n")
        lines.append("  }\n")
    lines.append("  return specs;\n")
    lines.append("}\n")
    return "".join(lines)


def emit_metamorphic(records: list[dict[str, Any]]) -> str:
    lines = [
        HEADER,
        "\n",
        "static std::vector<MetamorphicSpec> GeneratedMetamorphicOracleSpecs() {\n",
        "  std::vector<MetamorphicSpec> specs;\n",
    ]
    for entry in records:
        lines.append("  {\n")
        lines.append("    MetamorphicSpec spec;\n")
        lines.append(f"    spec.oracle_id = {cpp_string(entry['oracle_id'])};\n")
        lines.append(f"    spec.primitive_type = {cpp_string(entry['primitive_type'])};\n")
        lines.append(f"    spec.field = {cpp_string(entry['field'])};\n")
        lines.append(f"    spec.expected_relation = {cpp_string(entry['expected_relation'])};\n")
        lines.append(f"    spec.finding_subclass = {cpp_string(entry['finding_subclass'])};\n")
        rng = "true" if entry.get("requires_rng_injection") else "false"
        lines.append(f"    spec.uses_rng = {rng};\n")
        emit_metadata(lines, entry)
        lines.append("    specs.push_back(std::move(spec));\n")
        lines.append("  }\n")
    lines.append("  return specs;\n")
    lines.append("}\n")
    return "".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated files are current")
    args = parser.parse_args(argv)

    fips = emit_fips(read_specs(FIPS_FILES, metamorphic=False))
    metamorphic = emit_metamorphic(read_specs(METAMORPHIC_FILES, metamorphic=True))

    outputs = [(FIPS_OUTPUT, fips), (METAMORPHIC_OUTPUT, metamorphic)]
    if args.check:
        stale = [path for path, content in outputs if not path.is_file() or path.read_text(encoding="utf-8") != content]
        if stale:
            for path in stale:
                print(f"stale generated oracle specs: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return 1
        print("generated oracle specs are current")
        return 0

    for path, content in outputs:
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
