#!/usr/bin/env python3
"""Generate the checked-in KAT vector table from pinned NIST ACVP JSON files.

Input:  third_party/kat/acvp-<commit>/ (fetched by scripts/fetch_kat_vectors.sh)
Output: src/oracles/kat/generated_kat_vectors.inc

The checked-in table is a capped subset (default 3 cases per parameter set and
operation) so the repository stays small.  The manifest records the source
commit, per-file SHA-256 digests, and the total case counts seen while parsing.

Usage:
    python3 scripts/parse_kat_vectors.py            # write the include
    python3 scripts/parse_kat_vectors.py --check    # fail if stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "src" / "oracles" / "kat" / "generated_kat_vectors.inc"
MANIFEST = REPO_ROOT / "src" / "oracles" / "kat" / "generated_kat_vectors.manifest.json"
ACVP_COMMIT = "975de31eb83d87039ec88934fdc47d8c312b892d"
KAT_ROOT = REPO_ROOT / "third_party" / "kat" / f"acvp-{ACVP_COMMIT}"
DEFAULT_LIMIT = 3

HEADER = "// Generated by scripts/parse_kat_vectors.py. DO NOT EDIT.\n"


def load_pair(directory: str) -> tuple[dict[str, Any], dict[str, Any]]:
    prompt = json.loads((KAT_ROOT / directory / "prompt.json").read_text(encoding="utf-8"))
    expected = json.loads((KAT_ROOT / directory / "expectedResults.json").read_text(encoding="utf-8"))
    return prompt, expected


def index_expected(expected: dict[str, Any]) -> dict[int, dict[str, Any]]:
    indexed: dict[int, dict[str, Any]] = {}
    for group in expected.get("testGroups", []):
        for test in group.get("tests", []):
            indexed[int(test["tcId"])] = test
    return indexed


def kem_keygen(limit: int) -> tuple[list[tuple[str, str, str, str, str, str, str]], int]:
    prompt, expected = load_pair("ML-KEM-keyGen-FIPS203")
    expected_by_id = index_expected(expected)
    vectors: list[tuple[str, str, str, str, str, str, str]] = []
    seen = 0
    for group in prompt.get("testGroups", []):
        parameter_set = str(group.get("parameterSet", ""))
        for test in group.get("tests", []):
            seen += 1
            if len([v for v in vectors if v[1] == parameter_set]) >= limit:
                continue
            result = expected_by_id.get(int(test["tcId"]))
            if result is None:
                continue
            vectors.append((
                "F203-KAT-KG-INT",
                parameter_set,
                "keygen",
                str(test["d"]),
                str(test["z"]),
                "",
                str(result["ek"]),
                str(result["dk"]),
            ))
    return vectors, seen


def kem_encap_decap(limit: int) -> tuple[list[tuple[str, str, str, str, str, str, str]], int]:
    prompt, expected = load_pair("ML-KEM-encapDecap-FIPS203")
    expected_by_id = index_expected(expected)
    vectors: list[tuple[str, str, str, str, str, str, str]] = []
    seen = 0
    counts: dict[tuple[str, str], int] = {}
    for group in prompt.get("testGroups", []):
        parameter_set = str(group.get("parameterSet", ""))
        function = str(group.get("function", ""))
        for test in group.get("tests", []):
            seen += 1
            key = (parameter_set, function)
            if counts.get(key, 0) >= limit:
                continue
            result = expected_by_id.get(int(test["tcId"]))
            if result is None:
                continue
            if function == "encapsulation":
                vectors.append((
                    "F203-KAT-ENC-INT",
                    parameter_set,
                    "encaps",
                    str(test["ek"]),
                    str(test["m"]),
                    "",
                    str(result["c"]),
                    str(result["k"]),
                ))
            elif function == "decapsulation":
                vectors.append((
                    "F203-KAT-DEC-INT",
                    parameter_set,
                    "decaps",
                    str(test["dk"]),
                    str(test["c"]),
                    "",
                    str(result["k"]),
                    "",
                ))
            else:
                continue
            counts[key] = counts.get(key, 0) + 1
    return vectors, seen


def slh_keygen(limit: int) -> tuple[list[tuple[str, str, str, str, str, str, str]], int]:
    prompt, expected = load_pair("SLH-DSA-keyGen-FIPS205")
    expected_by_id = index_expected(expected)
    vectors: list[tuple[str, str, str, str, str, str, str]] = []
    seen = 0
    counts: dict[str, int] = {}
    for group in prompt.get("testGroups", []):
        parameter_set = str(group.get("parameterSet", ""))
        for test in group.get("tests", []):
            seen += 1
            if counts.get(parameter_set, 0) >= limit:
                continue
            result = expected_by_id.get(int(test["tcId"]))
            if result is None:
                continue
            seed = (
                str(test.get("skSeed", ""))
                + str(test.get("skPrf", ""))
                + str(test.get("pkSeed", ""))
            )
            vectors.append((
                "F205-KAT-KG-INT",
                parameter_set,
                "slh_seed_keygen",
                seed,
                "",
                "",
                str(result["pk"]),
                str(result["sk"]),
            ))
            counts[parameter_set] = counts.get(parameter_set, 0) + 1
    return vectors, seen


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def emit(vectors: list[tuple[str, str, str, str, str, str, str]], manifest: dict[str, Any]) -> str:
    lines = [HEADER, "\n", "static std::vector<KATVector> GeneratedKatVectors() {\n", "  std::vector<KATVector> vectors;\n"]
    for case_id, parameter_set, operation, input_a, input_b, input_c, expected_a, expected_b in vectors:
        lines.append(
            "  vectors.push_back({"
            + ", ".join(cpp_string(item) for item in (
                case_id,
                parameter_set,
                operation,
                input_a,
                input_b,
                input_c,
                expected_a,
                expected_b,
            ))
            + "});\n"
        )
    lines.append("  return vectors;\n")
    lines.append("}\n")
    return "".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--limit", type=int, default=DEFAULT_LIMIT)
    args = parser.parse_args(argv)

    if not KAT_ROOT.is_dir():
        print(f"missing ACVP vectors: {KAT_ROOT}; run scripts/fetch_kat_vectors.sh", file=sys.stderr)
        return 1

    keygen_vectors, keygen_seen = kem_keygen(args.limit)
    encap_vectors, encap_seen = kem_encap_decap(args.limit)
    slh_vectors, slh_seen = slh_keygen(args.limit)
    vectors = keygen_vectors + encap_vectors + slh_vectors

    manifest = {
        "source": "usnistgov/ACVP-Server",
        "commit": ACVP_COMMIT,
        "limit_per_parameter_set": args.limit,
        "vector_count": len(vectors),
        "seen": {
            "ML-KEM-keyGen-FIPS203": keygen_seen,
            "ML-KEM-encapDecap-FIPS203": encap_seen,
            "SLH-DSA-keyGen-FIPS205": slh_seen,
        },
        "files": {},
    }
    for path in sorted(KAT_ROOT.glob("*/*.json")):
        manifest["files"][str(path.relative_to(KAT_ROOT))] = hashlib.sha256(path.read_bytes()).hexdigest()

    content = emit(vectors, manifest)
    manifest_content = json.dumps(manifest, indent=2, sort_keys=True) + "\n"

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        current_manifest = MANIFEST.read_text(encoding="utf-8") if MANIFEST.is_file() else ""
        if current != content or current_manifest != manifest_content:
            print("generated KAT vectors are stale; rerun scripts/parse_kat_vectors.py", file=sys.stderr)
            return 1
        print("generated KAT vectors are current")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    MANIFEST.write_text(manifest_content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(vectors)} vectors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
